cd:
  name: Deploy to VPS
  runs-on: ubuntu-latest
  needs: ci

  steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker pull prashant4593/dgaid-frontend:latest
          docker pull prashant4593/dgaid-backend:latest

          docker stop frontend || true
          docker rm frontend || true
          docker stop backend || true
          docker rm backend || true

          docker run -d --name frontend -p 80:80 prashant4593/dgaid-frontend:latest
          docker run -d --name backend -p 3000:3000 prashant4593/dgaid-backend:latest
