name: Frontend Auto CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install & Build Frontend
        working-directory: ./app/Frontend
        run: |
          npm install
          npm run build

      - name: Copy Frontend to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "app/Frontend"
          target: ${{ secrets.VPS_PATH }}

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/app/Frontend
            docker rm -f frontend || true
            docker build -t frontend-app .
            docker run -d --name frontend -p 3000:80 frontend-app
